version: "3.8"
services:
  api:
    volumes:
      - ./backend/uploads:/adam/src/app/uploads
    build: 
      dockerfile: Dockerfile
      context: ./backend
    depends_on: 
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:1910008@postgres:5432/blog 
      NODE_ENV: development
      PORT: 8080
    ports:
      - "8080:8080"
    
  postgres:
    image: postgres:15.4
    ports:
      - "35000:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1910008
      POSTGRES_DB: blog
    volumes:
       - ./backend/data:/var/lib/postgresql/data

  react-app:
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - "4000:4000"
    

          