version: "3.8"
services:
  api:
    #image: adam-bista/nestjs-dockerized
    build: 
      dockerfile: Dockerfile
      context: .
    depends_on: 
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:1910008@postgres:5432/blog 
      NODE_ENV: development
      PORT: 3000
    ports:
      - "8080:3000"
    
  postgres:
    image: postgres:15.4
    ports:
      - "35000:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1910008
      POSTGRES_DB: blog
    volumes:
       - ./data:/var/lib/postgresql/data
    

          